### ISSUE TITLE
Broken DOI link in publications.md for "'Ruthless Criticism of All That Exists': Marxism, Technology, and Library Work"

### ISSUE THREAD

**Issue by cudevmaxwell** [redlibrarian/redlibrarian.github.io#3]
https://doi.org/10.7939/R3RF5KV47 redirects to https://datacite.org/invalid.html

**Comment by redlibrarian** [comment]
@cudevmaxwell Sigh - that's the autogenerated one from our IR. Thanks for letting me know - I'll find out what's up!

**Comment by redlibrarian** [comment]
@cudevmaxwell BTW think actual URL is: https://era.library.ualberta.ca/items/048f1970-8324-41aa-a993-bace2b9257c2

**Comment by redlibrarian** [comment]
Forgot to close this. Our IR team minted a new DOI to fix the problem.
